"use client";

import { useState } from "react";
import { plainPlannerText, plainPlannerErrors } from "../components/planner-copy";
import Link from "next/link";
import { NumberControl } from "../components/number-control";
import { LucidFlexPlanner } from "../components/lucidflex-planner";
import { TradeifySelectFlexPlanner } from "../components/tradeify-select-flex-planner";
import { TradeifySelectDailyPlanner } from "../components/tradeify-select-daily-planner";
import { calculateTargets, projectAnnualIncome, formatUsd } from "@tradehq/domain";

type Period = "week" | "month" | "year";
type Mode = "trading" | "cash";
const defaults = { goalAmount: "5000", period: "month" as Period, activeDays: "20", accountCount: "5", mode: "trading" as Mode, payoutSharePercent: "90", accountCost: "50", dailyPerAccountAverage: "50", annualTradingDays: "240" };
const periodNames = { week: "week", month: "month", year: "year" };
const defaultDays = { week: "5", month: "20", year: "240" };

export default function CalculatorPage() {
  const [inputs, setInputs] = useState(defaults);
  const [planner, setPlanner] = useState<"generic" | "lucidflex" | "tradeify" | "tradeifydaily">("lucidflex");
  const [resetVersion, setResetVersion] = useState(0);
  const set = (key: keyof typeof defaults, value: string) => setInputs(old => ({ ...old, [key]: value }));
  const result = calculateTargets(inputs);
  const projection = projectAnnualIncome(inputs);
  const errors = result.ok ? {} : plainPlannerErrors(result.errors);
  const annualErrors = projection.ok ? {} : plainPlannerErrors(projection.errors);
  const maximumDays = inputs.period === "week" ? 7 : inputs.period === "month" ? 31 : 366;
  const choosePeriod = (period: Period) => setInputs(old => ({ ...old, period, activeDays: defaultDays[period] }));
  const rows = projection.ok ? projection.value.scaling : [];
  const chartRows = rows.filter(row => row.accountCount === 1 || row.accountCount === Number(inputs.accountCount) || row.accountCount === Math.ceil(Number(inputs.accountCount) / 2));
  const chartMax = Math.max(1, ...chartRows.map(row => Math.abs(Number(row.annualTradingPnl))));
  return <div className="app-shell">
    <aside className="sidebar" aria-label="Workspace">
      <a className="brand" href="#main"><span className="brand-mark">T<span>H</span></span>TradeHQ<span className="brand-dot">.</span></a>
      <div className="workspace-label">TRADING WORKSPACE</div>
      <div className="nav-current"><span className="nav-glyph" aria-hidden="true">▦</span>Income planner<span className="nav-current-dot" /></div>
      <Link className="nav-link" href="/imports">Imports <span aria-hidden="true">↗</span></Link>
      <div className="future-label">ON THE ROADMAP</div>
      <div className="future-nav"><span>Trade journal</span><span>Accounts</span><span>Cash ledger</span></div>
      <div className="sidebar-bottom"><span className="prototype-dot" />Calculator prototype<p>Your next move,<br />with the numbers in view.</p><div className="sidebar-meta">USD · INCOME SCENARIOS</div></div>
    </aside>
    <div className="workspace">
      <header className="topbar"><span>Workspace <span className="breadcrumb-separator">/</span> <strong>Income planner</strong></span><span className="topbar-tag">SCENARIO MODE</span></header>
      <main id="main">
        <div className="page-heading"><div><p className="eyebrow">PLAN WITH INTENTION</p><h1>Turn your goal into a daily plan<span>.</span></h1><p className="intro">Set your goal. See the daily profit needed. Compare account counts.</p></div><button className="reset-button" onClick={() => { setInputs({ ...defaults }); setResetVersion(value => value + 1); }}>Reset assumptions <span aria-hidden="true">↺</span></button></div>
        <div className="planner-mode-selector four-planners" role="group" aria-label="Planning model"><button aria-pressed={planner === "lucidflex"} onClick={() => setPlanner("lucidflex")}><span>LucidFlex</span><small>Funded $50k · payout rules</small></button><button aria-pressed={planner === "tradeify"} onClick={() => setPlanner("tradeify")}><span>Tradeify Select Flex</span><small>Funded $50k · example payout rules</small></button><button aria-pressed={planner === "tradeifydaily"} onClick={() => setPlanner("tradeifydaily")}><span>Tradeify Select Daily</span><small>Funded $50k · daily request rules</small></button><button aria-pressed={planner === "generic"} onClick={() => setPlanner("generic")}><span>Generic planning</span><small>Simple goals &amp; account comparisons</small></button></div>
        {planner === "lucidflex" ? <LucidFlexPlanner key={resetVersion} /> : planner === "tradeify" ? <TradeifySelectFlexPlanner key={resetVersion} /> : planner === "tradeifydaily" ? <TradeifySelectDailyPlanner key={resetVersion} /> : <><div className="planner-layout">
          <section className="assumptions-panel" aria-labelledby="assumptions-title">
            <div className="section-heading"><span className="section-number">01</span><h2 id="assumptions-title">Set your target</h2><span className="currency-tag">USD</span></div>
            <div className="goal-controls"><label htmlFor="goal">I want to make</label><div className={`goal-input ${errors.goalAmount ? "invalid" : ""}`}><span>$</span><input id="goal" type="number" inputMode="decimal" min="0" max="1000000000000" step="0.01" value={inputs.goalAmount} onChange={e => set("goalAmount", e.target.value)} aria-invalid={!!errors.goalAmount} aria-describedby={errors.goalAmount ? "goal-error" : undefined} /></div>{errors.goalAmount && <p className="field-error" id="goal-error">{errors.goalAmount}</p>}<input className="slider" type="range" aria-label="Goal amount slider" min="0" max="100000" step="100" value={Math.min(100000, Number(inputs.goalAmount) || 0)} onChange={e => set("goalAmount", e.target.value)} /><div className="segmented period-selector" role="group" aria-label="Goal period">{(["week", "month", "year"] as Period[]).map(period => <button key={period} aria-pressed={inputs.period === period} onClick={() => choosePeriod(period)}>Per {period}</button>)}</div></div>
            <div className="basis-label">WHAT ARE YOU PLANNING?</div><div className="basis-selector" role="group" aria-label="Goal basis"><button aria-pressed={inputs.mode === "trading"} onClick={() => set("mode", "trading")}><span>Trading profit</span><small>After commissions &amp; trading fees</small></button><button aria-pressed={inputs.mode === "cash"} onClick={() => set("mode", "cash")}><span>Payout estimate</span><small>Your share, after account costs</small></button></div>
            <div className="fields-group"><NumberControl id="days" label="Days you plan to trade" value={inputs.activeDays} onChange={value => set("activeDays", value)} min={1} max={maximumDays} error={errors.activeDays} hint={`Days you plan to trade in this ${inputs.period}.`} /><NumberControl id="accounts" label="Number of accounts" value={inputs.accountCount} onChange={value => set("accountCount", value)} min={1} max={100} error={errors.accountCount} hint="Equal targets across all active accounts." /></div>
            {inputs.mode === "cash" && <div className="cash-controls"><div className="cash-heading">Payout inputs <span>ESTIMATE ONLY</span></div><NumberControl id="share" label="Your payout share" value={inputs.payoutSharePercent} onChange={value => set("payoutSharePercent", value)} max={100} step={0.1} suffix="%" error={errors.payoutSharePercent} /><div><NumberControl id="costs" label={`Account cost / ${inputs.period}`} value={inputs.accountCost} onChange={value => set("accountCost", value)} max={10000} step={0.01} prefix="$" error={errors.accountCost} hint="Cost per account this period: purchases, resets, activation or platform fees. Leave out trading fees already deducted from profit." />{result.ok && <p className="cost-equation">${inputs.accountCost}/account × {inputs.accountCount} accounts = <strong>{formatUsd(result.value.portfolioCosts)}</strong> this {inputs.period}</p>}<p className="cost-period-note">Enter the cost for this period; changing periods does not convert it or make purchases recurring.</p></div><p className="cash-disclosure">Assumes all trading profit can be paid during this period. Firm payout rules and payment delays are not included.</p></div>}
            <p className="account-note">$50k names an account size, not your own money. It does not change this calculation.</p>
          </section>
          <div className="results-column">
            <section className={`target-panel ${!result.ok ? "target-invalid" : ""}`} aria-labelledby="target-title">
              <div className="target-heading"><p className="eyebrow">DAILY PROFIT NEEDED</p><span className="result-tag">{inputs.mode === "trading" ? "TRADING PROFIT" : "SIMPLE PAYOUT ESTIMATE"}</span></div>
              {result.ok ? <><h2 id="target-title">{formatUsd(result.value.dailyPerAccountTarget)}<span>/ account</span></h2><p className="target-subtitle">per day you trade, across {inputs.accountCount} {inputs.accountCount === "1" ? "account" : "accounts"}</p><div className="target-divider" /><div className="target-support"><div><span>Daily profit · all accounts</span><strong>{formatUsd(result.value.dailyPortfolioTarget)}</strong></div><div><span>Trading profit needed / {periodNames[inputs.period]}</span><strong>{formatUsd(result.value.tradingTarget)}</strong></div></div>{inputs.mode === "cash" && <div className="target-cost-bridge"><span>Total account costs</span><strong>{formatUsd(result.value.portfolioCosts)}</strong><p>${inputs.accountCost}/account × {inputs.accountCount} accounts in the selected {inputs.period}</p></div>}<div className="target-equation"><span>{inputs.activeDays} trading days</span><span aria-hidden="true">×</span><span>{inputs.accountCount} accounts</span><span aria-hidden="true">→</span><span>{formatUsd(inputs.goalAmount)} {inputs.mode === "cash" ? "payout goal" : "trading profit goal"}</span></div></> : <div className="invalid-result" role="status"><h2 id="target-title">Let’s check the inputs.</h2><p>Fix the highlighted inputs to see the daily profit you need.</p><ul>{Object.values(errors).map((error, i) => <li key={i}>{error}</li>)}</ul></div>}
            </section>
            <section className="comparison-panel" aria-labelledby="comparison-title"><div className="section-heading"><span className="section-number">02</span><h2 id="comparison-title">Same goal. Different scale.</h2></div><p className="section-description">{inputs.mode === "cash" ? "Your payout goal stays the same. More accounts add costs before the daily profit needed is divided across them." : "More accounts divide the daily target. They don’t change the goal."}</p>{result.ok ? <div className="comparison-grid"><div className="comparison-single"><span className="comparison-label">ONE ACCOUNT</span><strong>{formatUsd(result.value.scaling[0].dailyPerAccountTarget)}</strong><span>per account / trading day</span>{inputs.mode === "cash" && <span>{formatUsd(result.value.scaling[0].portfolioCosts)} account costs</span>}</div><div className="comparison-selected"><span className="comparison-label">{inputs.accountCount} {inputs.accountCount === "1" ? "ACCOUNT" : "ACCOUNTS"}</span><strong>{formatUsd(result.value.dailyPerAccountTarget)}</strong><span>per account / trading day</span>{inputs.mode === "cash" && <span>{formatUsd(result.value.portfolioCosts)} account costs</span>}</div></div> : <p className="unavailable">Comparison available after correcting target inputs.</p>}{result.ok && inputs.mode === "cash" && <details className="cash-scaling-details"><summary>Compare daily profit and costs for each account count</summary><div className="table-scroll"><table><caption>Same payout goal with {formatUsd(inputs.accountCost)} per account / {inputs.period}</caption><thead><tr><th scope="col">Accounts</th><th scope="col">Account costs</th><th scope="col">Daily target / account</th></tr></thead><tbody>{result.value.scaling.map(row => <tr key={row.accountCount}><th scope="row">{row.accountCount}</th><td>{formatUsd(row.portfolioCosts)}</td><td>{formatUsd(row.dailyPerAccountTarget)}</td></tr>)}</tbody></table></div></details>}<p className="comparison-note">Copied trades can lose together. This comparison uses equal profit per account; more accounts also add costs.</p></section>
          </div>
        </div>
        <section className="annual-panel" aria-labelledby="annual-title"><div className="annual-intro"><div className="section-heading"><span className="section-number">03</span><h2 id="annual-title">What could a year look like?</h2></div><p className="section-description">Estimate yearly trading profit using a separate daily average.</p><div className="annual-controls"><NumberControl id="average" label="Average daily profit per account" value={inputs.dailyPerAccountAverage} onChange={value => set("dailyPerAccountAverage", value)} min={-1000} max={1000} step={0.01} prefix="$" error={annualErrors.dailyPerAccountAverage} hint="After commissions and trading fees, averaged across winning and losing days. Skipped days are excluded." /><NumberControl id="annual-days" label="Trading days this year" value={inputs.annualTradingDays} onChange={value => set("annualTradingDays", value)} min={1} max={366} error={annualErrors.annualTradingDays} /></div></div><div className="annual-results">{projection.ok ? <><span className="annual-result-label">ESTIMATED YEARLY TRADING PROFIT</span><div className={`annual-amount ${Number(projection.value.annualTradingPnl) < 0 ? "negative" : ""}`}>{formatUsd(projection.value.annualTradingPnl)}</div><p>{inputs.accountCount} accounts · {inputs.annualTradingDays} trading days · {formatUsd(inputs.dailyPerAccountAverage)} average / account / day</p><div className="scaling-chart" role="img" aria-label="Yearly trading profit by account count. Exact values appear in the table below.">{chartRows.map(row => <div className="chart-row" key={row.accountCount}><span>{row.accountCount} {row.accountCount === 1 ? "account" : "accounts"}</span><div className="chart-track"><div className={`chart-bar ${Number(row.annualTradingPnl) < 0 ? "loss" : ""}`} style={{ width: `${Math.abs(Number(row.annualTradingPnl)) / chartMax * 100}%` }} /></div><strong>{formatUsd(row.annualTradingPnl)}</strong></div>)}</div><details><summary>Compare each account count</summary><div className="table-scroll"><table><caption>Yearly estimate with the same daily profit and trading days</caption><thead><tr><th scope="col">Accounts</th><th scope="col">Yearly trading profit</th></tr></thead><tbody>{rows.map(row => <tr key={row.accountCount}><th scope="row">{row.accountCount}</th><td>{formatUsd(row.annualTradingPnl)}</td></tr>)}</tbody></table></div></details></> : <div className="annual-error" role="status"><h3>Yearly estimate unavailable</h3><ul>{Object.values(annualErrors).map((error, i) => <li key={i}>{error}</li>)}</ul></div>}</div></section>
        </>}
        <footer className="calculation-footer"><div><strong>Know what goes into the estimate.</strong><p>USD. Amounts shown to two decimal places; calculations keep full precision. These are estimates, not money received. LucidFlex stops after payout 5; Tradeify estimates stop before possible live review. Later income is not included.</p></div><span className="footer-wordmark">TradeHQ<span>.</span></span></footer>
      </main>
    </div>
  </div>;
}
