"""Render the current milestone board without third-party dependencies."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
STATES = {"open", "blocked", "in progress", "in review", "merged", "validated", "dropped"}


def load_board(root: Path) -> tuple[str, dict]:
    milestone = (root / "docs/milestones/CURRENT").read_text(encoding="utf-8").strip()
    if not milestone or not milestone.isalnum() or not milestone.startswith("M"):
        raise ValueError("CURRENT must contain a milestone ID such as M0")
    # JSON is a strict subset of YAML 1.2; these boards deliberately use JSON syntax.
    board = json.loads((root / f"docs/milestones/{milestone}.yaml").read_text(encoding="utf-8"))
    if not isinstance(board, dict):
        raise ValueError("board must be an object")
    for name in ("exit_criteria", "validates_against", "blockers", "tasks"):
        if name not in board or not isinstance(board[name], list):
            raise ValueError(f"board.{name} must be a list")
    for name in ("exit_criteria", "validates_against", "blockers"):
        if any(not isinstance(item, str) or not item.strip() for item in board[name]):
            raise ValueError(f"board.{name} must contain nonempty strings")
    ids = set()
    for task in board["tasks"]:
        if not isinstance(task, dict):
            raise ValueError("each task must be an object")
        for name in ("id", "title", "package", "owner", "state", "notes"):
            if not isinstance(task.get(name), str) or not task[name].strip():
                raise ValueError(f"task.{name} must be a nonempty string")
        for name in ("reviewers", "blocked_by", "matrix", "spec", "docs"):
            if not isinstance(task.get(name), list) or any(not isinstance(x, str) or not x.strip() for x in task[name]):
                raise ValueError(f"{task['id']}.{name} must be a list of nonempty strings")
        if not task["reviewers"] or not task["matrix"] or not task["spec"]:
            raise ValueError(f"{task['id']} needs reviewers, matrix cases and specs")
        if "adr" not in task or not (task["adr"] is None or isinstance(task["adr"], str)):
            raise ValueError(f"{task['id']}.adr must be a path or null")
        if task["state"] not in STATES:
            raise ValueError(f"{task['id']} has invalid state: {task['state']}")
        if not task["id"].startswith(milestone + "-") or task["id"] in ids:
            raise ValueError(f"invalid or duplicate task ID: {task['id']}")
        ids.add(task["id"])
    task_map = {task["id"]: task for task in board["tasks"]}
    for task in board["tasks"]:
        for dependency in task["blocked_by"]:
            if dependency not in ids or dependency == task["id"]:
                raise ValueError(f"{task['id']} has invalid dependency {dependency}")
        if task["state"] in {"merged", "validated"} and any(task_map[x]["state"] not in {"merged", "validated"} for x in task["blocked_by"]):
            raise ValueError(f"{task['id']} completed before its dependencies")
    def visit(task_id: str, active: set[str], done: set[str]) -> None:
        if task_id in active:
            raise ValueError(f"dependency cycle at {task_id}")
        if task_id in done:
            return
        active.add(task_id)
        for dependency in task_map[task_id]["blocked_by"]:
            visit(dependency, active, done)
        active.remove(task_id)
        done.add(task_id)
    done: set[str] = set()
    for task_id in ids:
        visit(task_id, set(), done)
    return milestone, board


def cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def render(root: Path) -> str:
    milestone, board = load_board(root)
    lines = ["# TradeHQ status", "", "<!-- Generated by tools/status/render.py. Do not edit by hand. -->", "", f"Current milestone: **{milestone}**", "", "## Exit criteria", ""]
    lines.extend(f"- {item}" for item in board["exit_criteria"])
    lines.extend(["", "## Validates against", ""])
    lines.extend(f"- {item}" for item in board["validates_against"])
    lines.extend(["", "## Blockers", ""])
    lines.extend(f"- {item}" for item in board["blockers"])
    if not board["blockers"]:
        lines.append("None recorded.")
    lines.extend(["", "## Tasks", "", "| ID | Task | Owner | Reviewers | State | Dependencies | Matrix |", "| --- | --- | --- | --- | --- | --- | --- |"])
    for task in board["tasks"]:
        values = [task["id"], task["title"], task["owner"], ", ".join(task["reviewers"]), task["state"], ", ".join(task["blocked_by"]) or "None", ", ".join(task["matrix"])]
        lines.append("| " + " | ".join(cell(v) for v in values) + " |")
    lines.extend(["", "## Task details", ""])
    for task in board["tasks"]:
        lines.extend([f"### {task['id']}", "", f"- Package: `{task['package']}`", f"- ADR: {task['adr'] or 'None required'}", f"- Spec: {', '.join(task['spec'])}", f"- Docs: {', '.join(task['docs']) or 'None'}", f"- Notes: {task['notes']}", ""])
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if STATUS.md differs from the board")
    args = parser.parse_args()
    try:
        expected = render(ROOT)
        target = ROOT / "STATUS.md"
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != expected:
                print("STATUS.md is stale; run python tools/status/render.py", file=sys.stderr)
                return 1
            print("STATUS.md matches the board")
        else:
            target.write_text(expected, encoding="utf-8", newline="\n")
            print("Rendered STATUS.md")
    except (ValueError, OSError) as error:
        print(f"Board error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
